window.CLI_COURSE = window.CLI_COURSE || { modules: [], exam: null, cheatsheet: null };
window.CLI_COURSE.exam = {
  id: "exam", title: "Фінальний іспит", passPercent: 80,
  quiz: [
    { title: "Шлях меню", question: "Що в команді `/interface wireguard peers print` є дією?", options: ["`/interface`", "`wireguard peers`", "`print`"], correct: 2, feedback: "`/interface wireguard peers` — шлях до меню, `print` — дія «показати»." },
    { title: "Пошук команд", question: "Ти в терміналі RouterOS 7 і не пам'ятаєш, які підменю є в `/ip`. Найшвидший спосіб?", options: ["Надрукувати `/ip ` і натиснути Tab двічі або F1", "Шукати в інтернеті", "Перебирати назви навмання з Enter"], correct: 0, feedback: "Вбудовані підказки завжди відповідають твоїй версії й пакетам." },
    { title: "Дії", question: "Яка з дій змінює конфігурацію одразу після Enter?", options: ["`print detail`", "`set`", "`print where …`"], correct: 1, feedback: "`set`, `add`, `remove`, `enable`, `disable` застосовуються миттєво." },
    { title: "Safe Mode", question: "Ти збираєшся віддалено змінити правила firewall. Правильна послідовність?", options: ["Зміни → Ctrl+X → export", "Reset → зміни → backup", "`print detail` → `/export` → Ctrl+X (Safe Mode) → одна зміна → перевірка"], correct: 2, feedback: "Спершу стан і копія, потім страховка, потім невеликі кроки." },
    { title: "Safe Mode", question: "Під час роботи в Safe Mode зв'язок обірвався. Що буде зі змінами?", options: ["Роутер їх відкотить після тайм-ауту сесії", "Вони залишаться", "Роутер скине всю конфігурацію"], correct: 0, feedback: "Саме від цього Safe Mode і захищає; ручний вихід Ctrl+X, навпаки, зміни зберігає." },
    { title: "Бекап", question: "Який файл підійде, щоб перенести частину налаштувань на роутер іншої моделі?", options: ["`.backup` з `/system backup save`", "`.rsc` з `/export file=…`", "Скріншот WinBox"], correct: 1, feedback: "Export — текст команд; бінарний backup розрахований на той самий пристрій." },
    { title: "Відкат", question: "Ти щойно вимкнув не той порт, зв'язок є. Найшвидший відкат однією командою?", options: ["`/system reset-configuration`", "`/import`", "`/undo`"], correct: 2, feedback: "`/undo` скасовує останню зміну; журнал змін — `/system history print`." },
    { title: "Ризик", question: "Яка команда за наслідками найнебезпечніша при віддаленій роботі?", options: ["`/system reset-configuration`", "`/system resource print`", "`/log print follow`"], correct: 0, feedback: "Скидання стирає всю конфігурацію, включно з адресою, через яку ти підключений." },
    { title: "Система", question: "Що покаже `/system package print` на RouterOS 7?", options: ["Список Wi‑Fi клієнтів", "Основний пакет `routeros` і опційні пакети (напр. `wifi-qcom-ac`, `container`)", "Правила NAT"], correct: 1, feedback: "Більшість функцій — у `routeros`; драйвери Wi‑Fi, контейнери тощо ставлять окремо." },
    { title: "Журнал", question: "Як показати лише записи журналу про firewall?", options: ["`/log print where topics~\"firewall\"`", "`/ip firewall filter print`", "`/log firewall print`"], correct: 0, feedback: "`where topics~…` фільтрує журнал за темою." },
    { title: "Діагностика", question: "`/tool traceroute 8.8.8.8`: шлюз провайдера відповідає, далі — 100% втрат. Висновок?", options: ["Зламаний Wi‑Fi вдома", "Неправильний DNS", "Проблема за шлюзом, у мережі провайдера"], correct: 2, feedback: "До першого вузла провайдера все гаразд — обрив далі." },
    { title: "Інтерфейси", question: "Новий пристрій у ether5 не отримує адресу, а в ether3 отримує. Перша перевірка?", options: ["`/interface bridge port print` — чи входить ether5 у bridge", "`/certificate print`", "`/system clock print`"], correct: 0, feedback: "DHCP-сервер LAN працює на bridge; порт поза ним сервера не чує." },
    { title: "Інтерфейси", question: "Ти підключений через ether2. Що з цього відріже тобі доступ?", options: ["`/interface print where disabled=yes`", "`/interface bridge port remove [find interface=ether2]`", "`/interface monitor-traffic ether2`"], correct: 1, feedback: "Дві інші команди лише читають." },
    { title: "IP", question: "Що показує `/ip neighbor print`?", options: ["Маршрути до сусідніх мереж", "Усі IP-адреси в інтернеті", "Сусідні пристрої, виявлені протоколами MNDP/CDP/LLDP"], correct: 2, feedback: "Це «хто поруч на кабелі»: інші MikroTik, комутатори з LLDP." },
    { title: "IP", question: "У `/ip route print` немає `0.0.0.0/0`, DHCP-клієнт на ether1 у стані `searching`. Що це означає?", options: ["Роутер не отримав адресу від провайдера — немає і маршруту в інтернет", "Зламаний DNS", "Вимкнено NAT"], correct: 0, feedback: "Маршрут за замовчуванням додає DHCP-клієнт після отримання адреси." },
    { title: "Firewall", question: "Правило, що дозволяє доступ, стоїть нижче за правило «drop усе з WAN». Що станеться?", options: ["Дозвіл спрацює, бо він точніший", "Спрацює drop — правила перевіряються згори вниз", "Роутер попросить обрати"], correct: 1, feedback: "Перше правило, що збіглося, вирішує долю пакета." },
    { title: "Доступ", question: "Як безпечно замінити стандартний обліковий запис `admin` на власний?", options: ["Вимкнути `admin` і створити новий", "Видалити всіх користувачів", "Створити `Stas` з групою `full`, перевірити вхід в окремій сесії, лише потім вимкнути `admin`"], correct: 2, feedback: "Спершу нові двері, потім зачиняєш старі." },
    { title: "IPsec", question: "`active-peers` показує `established`, а `installed-sa` порожній. Де проблема?", options: ["У policy/proposal — сторони не домовились, який трафік і чим шифрувати", "У кабелі", "У користувачах роутера"], correct: 0, feedback: "IKE пройшов; бракує SA — дивись policy, proposal і журнал `topics~\"ipsec\"`." },
    { title: "Сертифікати", question: "Що з цього безпечно надіслати колезі для налаштування довіри до твого VPN?", options: ["Файл `export-certificate` з приватним ключем", "Бекап роутера", "Публічний сертифікат CA без приватного ключа"], correct: 2, feedback: "Приватний ключ і бекап — секрети. Для довіри досить публічної частини." },
    { title: "Ключі", question: "Що означає прапорець `K` у `/certificate print`?", options: ["На роутері є приватний ключ сертифіката", "Сертифікат відкликано", "Сертифікат прострочено"], correct: 0, feedback: "K — PRIVATE-KEY: такий сертифікат роутер використовує від свого імені." }
  ]
};
